# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/ProductCatalog.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  imageName: 'mcr.microsoft.com/mssql/server:2019-latest'
  project: '**/API.csproj'

steps:

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '7.0.x'
  env:
    PROCESSOR_ARCHITECTURE: x64

- script: docker pull $(imageName)
  displayName: 'Docker pull...'


- task: DotNetCoreCLI@2
  displayName: 'Build for Market'
  inputs:
    command: 'publish'
    projects: '$(project)'
    publishWebProjects: True
    zipAfterPublish: True
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory) --self-contained false'
    
- task: PublishPipelineArtifact@1
  displayName: Publish Pipeline Artifacts for Market
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'Market'
