# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/ProductCatalog.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  imageName: 'mcr.microsoft.com/mssql/server:2019-latest'
  project: '**/API.csproj'

steps:

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '7.0.x'
  env:
    PROCESSOR_ARCHITECTURE: x64

- script: docker pull $(imageName)
  displayName: 'Docker pull images...'

- task: DotNetCoreCLI@2
  displayName: 'Restore packages for Product Catalog'
  inputs:
    command: restore
    projects: '$(solution)'

- task: DotNetCoreCLI@2
  displayName: 'Build Product Catalog'
  inputs:
    command: 'build'
    projects: '$(project)'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Test Product Catalog'
  inputs:
    command: 'test'
    projects: '**/ProductCatalog/tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Publish Product Catalog'
  inputs:
    command: 'publish'
    publishWebProjects: true
    zipAfterPublish: true
    projects: '$(project)'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

- task: PublishPipelineArtifact@1
  displayName: 'Publish Pipeline Artifact for Product Catalog'
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'Market'